mysql:
  image: mysql:5.7
  environment :
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=wordpress
  volumes:
    - db:/var/lib/mysql
web:
 image: wordpress
 links:
   - mysql
 environment:
   - WORDPRESS_DB_PASSWORD=123456
   - WORDPRESS_DB_USER=root 
 ports:
   - "127.0.0.3:8080:80"
 working_dir: /var/www/html
 volumes:
   - wordpress:/var/www/html
